apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - finance.ngenz.org
      secretName: finance-tls
  rules:
    - host: finance.ngenz.org
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: grafana
                port:
                  number: 3000
